<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Middleware\CheckUnresolvedWords::class => App\Middleware\CheckUnresolvedWordsFactory::class,
            App\Middleware\CheckWordsInWordExist::class => App\Middleware\CheckWordsInWordExistFactory::class,
            App\Middleware\CheckWordsInWordNotExist::class => App\Middleware\CheckWordsInWordNotExistFactory::class,
            App\Middleware\CheckWordsViaApi::class => App\Middleware\CheckWordsViaApiFactory::class,
            App\Middleware\GenerateWords::class => App\Middleware\GenerateWordsFactory::class,
            App\Middleware\DocumentManagerMiddleware::class => App\Middleware\DocumentManagerMiddlewareFactory::class,
            App\Middleware\Ok::class => App\Middleware\OkFactory::class,
            App\Middleware\RemoveResolvedWords::class => App\Middleware\RemoveResolvedWordsFactory::class,
            App\play\PlayTest::class => App\play\PlayTestFactory::class,
        ],
    ],
];
